# Generated by Django 5.0.4 on 2024-04-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_admin_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('Rol', models.CharField(blank=True, max_length=10, null=True)),
                ('Password', models.CharField(max_length=20)),
                ('PasswordChange', models.CharField(max_length=20)),
            ],
        ),
    ]
