# Generated by Django 5.0.4 on 2024-04-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
