# Generated by Django 5.0.4 on 2024-05-05 23:38

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterEstudent',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('PrimerNombre', models.CharField(max_length=200)),
                ('SegundoNombre', models.CharField(max_length=200)),
                ('PrimerApellido', models.CharField(max_length=200)),
                ('SegudnoApellido', models.CharField(max_length=200)),
                ('Sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('FechaNacimiento', models.DateField()),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.IntegerField()),
                ('Correo', models.EmailField(max_length=254, verbose_name=django.contrib.auth.models.User)),
                ('GradoAcademico', models.IntegerField(choices=[('', 'Seleccionar'), (0, 'Prescolar'), (1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto'), (6, 'Sexto'), (7, 'Septimo'), (8, 'Octavo'), (9, 'Noveno'), (10, 'Decimo'), (11, 'Onceavo')])),
                ('Contraseña', models.CharField(max_length=200)),
                ('rol', models.CharField(choices=[('Rector', 'Rector'), ('Docente', 'Docente'), ('Estudiante', 'Estudiante')], max_length=20)),
            ],
        ),
    ]
