# Generated by Django 5.0.4 on 2024-05-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buscar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GradoAcademico', models.IntegerField(choices=[('', 'Seleccionar'), (0, 'Prescolar'), (1, 'Primero'), (2, 'Segundo'), (3, 'Tercero'), (4, 'Cuarto'), (5, 'Quinto'), (6, 'Sexto'), (7, 'Septimo'), (8, 'Octavo'), (9, 'Noveno'), (10, 'Decimo'), (11, 'Onceavo')])),
            ],
        ),
        migrations.AlterField(
            model_name='registerestudent',
            name='Correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registerestudent',
            name='rol',
            field=models.CharField(choices=[('', 'Seleccionar'), ('Rector', 'Rector'), ('Docente', 'Docente'), ('Estudiante', 'Estudiante')], max_length=20),
        ),
    ]
