# Generated by Django 5.0.4 on 2024-05-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_estudiantes', '0002_buscar_alter_registerestudent_correo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buscar',
        ),
    ]
